14-feature-10-authentication-google
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-m22-k05-t1-reactive-01 pull request #18
Opened 2022-06-21 22:25 UTC by ayeza-zamudio3

# Description
Authenthication with google

2022-06-21 22:27 UTC, GerardoTovar approved these changes
looks good, just need to integrate it

2022-06-21 22:38 UTC, daniel-yocupicio submitted a review, later dismissed

2022-06-22 02:07 UTC, YilKanda requested changes

2022-06-22 02:07 UTC, YilKanda commented on App/src/libreria/authenticationGoogle.js
> +        '1023121760646-4o0p6e0meeogfe9he5poq2llq4oo873e.apps.googleusercontent.com',
Your Google ID should not appear on GitHub, use environment variables to hide it.

2022-06-22 02:07 UTC, YilKanda commented on App/src/libreria/authenticationGoogle.js
> +      console.log(error);
In GitHub, no debugging code should appear, such as console.log()

You can use Alert.alert() instead.

2022-06-22 02:07 UTC, YilKanda commented on App/src/libreria/authenticationGoogle.js
> +      console.log('Usuario agregado! => Enviando  A Home');
In GitHub, no debugging code should appear, such as console.log()

You can use Alert.alert() instead.

2022-06-22 02:07 UTC, YilKanda commented on App/src/libreria/authenticationGoogle.js
> +    .catch(error => console.log(error));
In GitHub, no debugging code should appear, such as console.log()

You can use Alert.alert() instead.

2022-06-22 02:07 UTC, YilKanda commented on App/src/libreria/authenticationGoogle.js
> +//const signIn = (firstname, suscribe, email, password, navigation)
Code that you do not use, delete it.

2022-06-27 14:38 UTC, YilKanda requested changes
Resolve conflicts that exist in your branch.

2022-06-27 14:38 UTC, YilKanda commented on App/.babelrc
> +  }
Add a blank line

2022-06-27 14:38 UTC, YilKanda commented on App/android/app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
Add a blank line

2022-07-04 22:57 UTC, closed without merging